# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MLPerf inference LLAMA2-70B

on:
  schedule:
    - cron: "59 04 * * *"

jobs:
  build_reference:
    if: github.repository_owner == 'gateoverflow'
    runs-on: [ self-hosted, GO-spr, linux, x64 ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]
        backend: [ "pytorch" ]
        device: [ "cpu" ]
        precision: [ "bfloat16" ]

    steps:
    - name: Test MLPerf Inference LLAMA2-70B reference implementation
      run: |
        source gh_action/bin/deactivate || python3 -m venv gh_action
        source gh_action/bin/activate
        export MLC_REPOS=$HOME/GH_MLC
        pip install cm4mlops
        pip install tabulate 
        cm pull repo
        pip install "huggingface_hub[cli]"
        git config --global credential.helper store
        huggingface-cli login --token ${{ secrets.HF_TOKEN }} --add-to-git-credential
        mlcr --tags=run-mlperf,inference,_submission,_short --submitter="MLCommons" --pull_changes=yes --pull_inference_changes=yes --model=llama2-70b-99 --implementation=reference --backend=${{ matrix.backend }} --precision=${{  matrix.precision }} --category=datacenter --scenario=Offline --execution_mode=test --device=${{ matrix.device }}  --docker --quiet --test_query_count=1 --target_qps=0.001 --docker_it=no --docker_mlc_repo=gateoverflow@mlperf-automations --adr.compiler.tags=gcc --hw_name=gh_action --docker_dt=yes  --results_dir=$HOME/gh_action_results --submission_dir=$HOME/gh_action_submissions --env.MLC_MLPERF_MODEL_LLAMA2_70B_DOWNLOAD_TO_HOST=yes  --clean
        mlcr --tags=push,github,mlperf,inference,submission --repo_url=https://github.com/mlcommons/mlperf_inference_test_submissions_v5.0 --repo_branch=auto-update --commit_message="Results from self hosted Github actions" --quiet --submission_dir=$HOME/gh_action_submissions
